#!/bin/bash
json1=$(jq '' /etc/wb-knxd-config.conf)
error=$(echo $json1 | jq '.Global.Error' | sed -e 's/\"//g') 					# "null" or "SomeText" ok
trace=$(echo $json1 | jq '.Global.Trace' | sed -e 's/\"//g') 					# "null" or "SomeText" ok
listenTcp=$(echo $json1 | jq '.LocalListener.ListenTcp' | sed -e 's/\"//g') 	# "null" or "SomeText" ok
listenLocal=$(echo $json1 | jq '.LocalListener.ListenLocal' | sed -e 's/\"//g') # "null" or "SomeText" ok
otherOptions=$(echo $json1 | jq '.Interface.OtherOptions' | sed -e 's/\"//g')   # "" or "SomeText"
name=$(echo $json1 | jq '.MulticastServer.Name'| sed -e 's/\"//g')  			# "" or "SomeText" ok
eibAddr=$(echo $json1 | jq '.Address.EibAddr' | sed -e 's/\"//g') 				# "SomeText" ok
clientAddrs=$(echo $json1 | jq '.Address.ClientAddrs' | sed -e 's/\"//g') 		# "SomeText" ok
layer2=$(echo $json1 | jq '.Interface.Layer2' | sed -e 's/\"//g') 				# "SomeText"
address=$(echo $json1 | jq '.MulticastServer.Address'| sed -e 's/\"//g') 		# "SomeText" ok
groupCache=$(echo $json1 | jq '.Cache.GroupCache' | sed -e 's/\"//g') 			# true/false/"null" ok
discovery=$(echo $json1 | jq '.MulticastServer.Discovery' | sed -e 's/\"//g') 	# true/false ok
tunnelling=$(echo $json1 | jq '.MulticastServer.Tunnelling' | sed -e 's/\"//g') # true/false ok
routing=$(echo $json1 | jq '.MulticastServer.Routing' | sed -e 's/\"//g') 		# true/false ok
server=$(echo $json1 | jq '.MulticastServer.Server' | sed -e 's/\"//g') 		# true/false ok
forced=$(echo $json1 | jq '.MulticastServer.Forced' | sed -e 's/\"//g') 		# true/false ok

if [[ "$error" = "null" ]]; then
	error=""
else
	error="-f$error"
fi

if [[ "$trace" = "null" ]]; then
	trace=""
else
	trace="-t$trace "
fi

if [[ "$listenTcp" = "null" ]]; then
	listenTcp=""
else
	listenTcp="-i $listenTcp "
fi

if [[ "$listenLocal" = "null" ]]; then
	listenLocal=""
else
	listenLocal="-u $listenLocal "
fi

if [[ "$groupCache" = "true" ]]; then
	groupCache="-c "
else
	groupCache=""
fi

if [[ "$server" = "true" ]]; then
	if [[ "$name" = "" ]]; then
		server="-S $address "
	else
		server="-n $name -S $address "
	fi
	if [[ "$discovery" = "true" ]]; then
		discovery="-D "
	else
		discovery=""
	fi
	if [[ "$tunnelling" = "true" ]]; then
		tunnelling="-T "
	else
		tunnelling=""
	fi
	if [[ "$routing" = "true" ]]; then
		routing="-R "
	else
		routing=""
	fi
	if [[ "$forced" = "true" ]]; then
		forced="--allow-forced-broadcast "
	else
		forced=""
	fi
else
	forced=""
	discovery=""
	tunnelling=""
	routing=""
	server=""
fi

#knxd [global-section] [address-section] [cache-section] [multicast-server-section] [local-listener-section] [interface-sections]
echo "# This file is automatically generated by /etc/wb-knxd-config.conf from wb-knxd-config. Do not edit manually." > /etc/knxd.conf
echo "KNXD_OPTS=\"$trace$error -e $eibAddr -E $clientAddrs $groupCache$forced$discovery$tunnelling$routing$server$listenTcp$listenLocal -b $layer2 $otherOptions\"" >> /etc/knxd.conf
service knxd restart
